### ISSUE TITLE
Installation requires many license agreements?

### ISSUE THREAD

**Issue by l3oxy** [farlee2121/BidirectionalMap#4]
When I try to install this NuGet to my "NetStandard 4.8" project, it unexpectedly prompts me to accept the license agreements of all of the following projects/namespaces, which seems excessive. If I do so, it adds many of these to my "packages.config" file. Is this something I am doing incorrectly?

System info:
- Microsoft Windows 11 Pro
- Microsoft Visual Studio Community 2022 (64-bit) - Current - Version 17.7.4
- Microsoft .NET Framework Version 4.8.09032

Packages/Namespaces to agree to:
- Microsoft.NETCore.Platforms
- Microsoft.Win32.Primitives
- NETStandard.Library
- System.Console
- System.Collections
- System.Collections.Consurrent
- System.AppContext
- System.Diagnostics.Debug
- System.Globilization.Calendars
- System.Diagnostics.Tools
- System.Diagnostics.Tracing
- System.IO.FileSystem.Primitives
- System.Globilization
- System.Net.Sockets
- System.IO.FileSystem
- System.Linq
- System.Xml.XDocument
- System.Net.Primitives
- System.ObjectModel
- System.Linq.Expressions
- System.Resources.ResourceManager
- System.Reflection.Primitives
- System.Runtime.Handles
- System.Runtime.Extensions
- System.Xml.ReaderWriter
- System.Reflection
- System.Runtime.InteropServices.RuntimeInformation
- System.Threading.Timer
- System.Runtime.Numerics
- System.Text.Encoding
- System.Text.Encoding.Extensions
- System.Runtime.InteropServices
- System.Text.RegularExpressions
- System.Threading
- System.Threading.Tasks

![image](https://github.com/farlee2121/BidirectionalMap/assets/42228543/a557ba84-feac-443b-91a7-a83a08fbd356)

**Comment by farlee2121** [comment]
Hmm. I don't believe there is a NetStandard 4.8 target framework moniker. 
NetFramework (the older windows-only version of .NET) didn't use transitive package dependencies, so adding a package adds all of its dependencies to your packages as well.

**Comment by l3oxy** [comment]
>NetFramework (the older windows-only version of .NET)

Correct, that one!

>so adding a package adds all of its dependencies to your packages as well.

Does that mean that this project (BidirectionalMap), depends on all of the packages I listed above?
Including `Sockets`, `FileSystem`, `RegularExpressions`, `Calendars`, `Reflection`, etc? 

I am not yet a C# wizard. 
It seems like the main file of this project is [BiMap.cs](https://github.com/farlee2121/BidirectionalMap/blob/main/BidirectionalMap/BiMap.cs), but when I look at this file, it does not seem (to me) to use these dependencies. 
Are these dependencies mostly required by the tests [BidirectionalMap.Tests](https://github.com/farlee2121/BidirectionalMap/tree/main/BidirectionalMap.Tests) and [BidirectionalMap.PropertyTests](https://github.com/farlee2121/BidirectionalMap/tree/main/BidirectionalMap.PropertyTests) ?

Thank you for all of your explanation

**Comment by farlee2121** [comment]
All of the above packages are part of the Base Class Library (BCL). In other words, they're basic elements of the .NET framework.

I'm not entirely sure why they're being included as packages. This library has no explicit package references and isn't directly using all those parts of the BCL.
If I had to guess, it's probably some kind of compatibility mechanism for older versions of .NET consuming netstandard packages. 
Linking and trimming are relatively new and in-progress features for .NET, so it probably doesn't have sophisticated logic for deciding the minimal necessary packages.

The test projects wouldn't affect the dependencies needed for the nuget packages. The core project has no dependence on them, and only the core project is considered when packing.
